# Generated by Django 5.1.4 on 2025-05-23 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_individualpoints'),
        ('programs', '0021_alter_guidedactivity_overview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individualpoints',
            options={'verbose_name': 'Individual Points', 'verbose_name_plural': 'Individual Points'},
        ),
        migrations.RemoveField(
            model_name='points',
            name='date_created',
        ),
        migrations.AddField(
            model_name='points',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_point_logs', to='programs.activity'),
        ),
        migrations.AddField(
            model_name='points',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_points', to='programs.program'),
        ),
        migrations.AddField(
            model_name='points',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='points',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_point_logs', to='programs.activitystep'),
        ),
    ]
