# Generated by Django 5.1.4 on 2025-06-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0006_userbadge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
    ]
