# Generated by Django 5.1.4 on 2025-03-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_remove_team_avatar_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='max_members',
            field=models.IntegerField(default=15),
        ),
    ]
