# Generated by Django 5.1.4 on 2026-04-15 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentalDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materials', models.TextField(blank=True, help_text='List all the materials and equipment you will need for your experiment.')),
                ('setup_description', models.TextField(blank=True, help_text='Describe how you will set up your experiment and the steps you will follow.')),
                ('setup_image', models.ImageField(blank=True, help_text='Upload a photo or diagram of your experimental setup.', null=True, upload_to='project_planner/setup_images/')),
                ('observations', models.TextField(blank=True, help_text='Record any qualitative observations you make during the experiment (what you see, smell, hear).')),
                ('data_table', models.TextField(blank=True, help_text='Use this space to collect your data. You can format it as a list or a simple table.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experimental_design', to='project_planner.project')),
            ],
        ),
    ]
