# Generated by Django 5.1.4 on 2026-04-15 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_planner', '0002_experimentaldesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_planner/experiment_photos/')),
                ('caption', models.CharField(blank=True, help_text='Briefly describe what is happening in this photo.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experimental_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_photos', to='project_planner.experimentaldesign')),
            ],
        ),
    ]
