# Generated by Django 5.1.4 on 2025-02-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_generated_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='generated_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='generated_avatars/'),
        ),
    ]
