# Generated by Django 5.1.4 on 2025-02-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_generated_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='generated_avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='generated_avatar_svg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
