# Generated by Django 5.1.4 on 2025-02-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_generated_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='generated_avatar_svg',
        ),
        migrations.AddField(
            model_name='profile',
            name='generated_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='generated_avatars/'),
        ),
    ]
