# Generated by Django 5.1.4 on 2025-02-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_generated_avatar_svg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accessory',
            field=models.CharField(choices=[('NONE', ''), ('EYEPATCH', 'eyepatch'), ('KURT', 'kurt'), ('PRESCRIPTION_1', 'prescription_01'), ('PRESCRIPTION_2', 'prescription_02'), ('ROUND', 'round'), ('SUNGLASSES', 'sunglasses'), ('WAYFARERS', 'wayfarers'), ('SUNGLASSES_2', 'sunglasses_2'), ('WAYFARERS_2', 'wayfarers_2')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='background_color',
            field=models.CharField(choices=[('DEFAULT', '#65C9FF'), ('BLACK', '#262E33'), ('WHITE', '#FFFFFF')], default='WHITE', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='clothing',
            field=models.CharField(choices=[('NONE', ''), ('BLAZER_SHIRT', 'blazer_shirt'), ('BLAZER_SWEATER', 'blazer_sweater'), ('COLLAR_SWEATER', 'collar_sweater'), ('GRAPHIC_SHIRT', 'graphic_shirt'), ('HOODIE', 'hoodie'), ('OVERALL', 'overall'), ('SHIRT_CREW_NECK', 'shirt_crew_neck'), ('SHIRT_SCOOP_NECK', 'shirt_scoop_neck'), ('SHIRT_V_NECK', 'shirt_v_neck'), ('ASTRONAUT_SUIT', 'astronaut_suit'), ('BOND_SUIT', 'bond_suit'), ('CHEF', 'chef'), ('GLADIATOR', 'gladiator'), ('JEDI_ROBE', 'jedi_robe'), ('SHIRT_WICK', 'shirt_wick')], default='HOODIE', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='clothing_color',
            field=models.CharField(choices=[('BLACK', '#262E33'), ('BLUE_01', '#65C9FF'), ('BLUE_02', '#5199E4'), ('BLUE_03', '#25557C'), ('GRAY_01', '#E6E6E6'), ('GRAY_02', '#929598'), ('HEATHER', '#3C4F5C'), ('PASTEL_BLUE', '#B1E2FF'), ('PASTEL_GREEN', '#A7FFC4'), ('PASTEL_ORANGE', '#FFDEB5'), ('PASTEL_YELLOW', '#FFFFB1'), ('PINK', '#FF488E'), ('RED', '#FF5C5C'), ('WHITE', '#FFFFFF')], default='PASTEL_GREEN', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='eye_type',
            field=models.CharField(choices=[('CLOSED', 'closed'), ('CRY', 'cry'), ('DEFAULT', 'default'), ('EYE_ROLL', 'eye_roll'), ('HAPPY', 'happy'), ('HEART', 'heart'), ('SIDE', 'side'), ('SQUINT', 'squint'), ('SURPRISED', 'surprised'), ('WINK_WACKY', 'wink_wacky'), ('WINK', 'wink'), ('X_DIZZY', 'x_dizzy')], default='DEFAULT', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='hair_color',
            field=models.CharField(choices=[('AUBURN', '#A55728'), ('BLACK', '#2C1B18'), ('BLONDE', '#B58143'), ('BLONDE_GOLDEN', '#D6B370'), ('BROWN', '#724133'), ('BROWN_DARK', '#4A312C'), ('PASTEL_PINK', '#F59797'), ('PLATINUM', '#ECDCBF'), ('RED', '#C93305'), ('SILVER_GRAY', '#E8E1E1')], default='BROWN', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='hair_type',
            field=models.CharField(choices=[('NONE', 'no_hair'), ('BIG_HAIR', 'big_hair'), ('BOB', 'bob'), ('BUN', 'bun'), ('CAESAR_SIDE_PART', 'caesar_side_part'), ('CAESAR', 'caesar'), ('CURLY', 'curly'), ('CURVY', 'curvy'), ('DREADS', 'dreads'), ('FRIDA', 'frida'), ('FRIZZLE', 'frizzle'), ('FRO_BAND', 'fro_band'), ('FRO', 'fro'), ('LONG_NOT_TOO_LONG', 'long_not_too_long'), ('MIA_WALLACE', 'mia_wallace'), ('SHAGGY_MULLET', 'shaggy_mullet'), ('SHAGGY', 'shaggy'), ('SHAVED_SIDES', 'shaved_sides'), ('SHORT_CURLY', 'short_curly'), ('SHORT_DREADS_1', 'short_dreads_1'), ('SHORT_DREADS_2', 'short_dreads_2'), ('SHORT_FLAT', 'short_flat'), ('SHORT_ROUND', 'short_round'), ('SHORT_WAVED', 'short_waved'), ('SIDES', 'sides'), ('STRAIGHT_1', 'straight_1'), ('STRAIGHT_2', 'straight_2'), ('STRAIGHT_STRAND', 'straight_strand'), ('ASTRONAUT', 'astronout'), ('BRAIDS', 'braids'), ('BRIDE', 'bride'), ('BUZZCUT', 'buzzcut'), ('CORNROWS', 'cornrows'), ('CURLY_2', 'curly_2'), ('DREADLOCKS', 'dreadlocks'), ('EINSTEIN_HAIR', 'einstein_hair'), ('ELVIS', 'elvis'), ('EVIL_SPIKE', 'evil_spike'), ('HALF_SHAVED', 'half_shaved'), ('HAT', 'hat'), ('LONG_HAIR_CURLY', 'long_hair_curly'), ('LOOSE_HAIR', 'loose_hair'), ('MOHAWK', 'mohawk'), ('MOWGLI', 'mowgli'), ('PIXIE', 'pixie'), ('POMPADOUR', 'pompadour'), ('QUIFF', 'quiff'), ('TWIST_LONG_HAIR', 'twist_long_hair'), ('TWIST_LONG_HAIR_2', 'twist_long_hair_2'), ('WICK', 'wick'), ('WILD', 'wild')], default='BOB', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='mouth_type',
            field=models.CharField(choices=[('CONCERNED', 'concerned'), ('DEFAULT', 'default'), ('DISBELIEF', 'disbelief'), ('EATING', 'eating'), ('GRIMACE', 'grimace'), ('SAD', 'sad'), ('SCREAM_OPEN', 'scream_open'), ('SERIOUS', 'serious'), ('SMILE', 'smile'), ('TONGUE', 'tongue'), ('TWINKLE', 'twinkle'), ('VOMIT', 'vomit'), ('BIG_SMILE', 'big_smile')], default='SMILE', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='shirt_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
