# Generated by Django 5.1.4 on 2025-02-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_accessory_profile_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='clothing',
            field=models.CharField(choices=[('NONE', ''), ('BLAZER_SHIRT', 'blazer_shirt'), ('BLAZER_SWEATER', 'blazer_sweater'), ('COLLAR_SWEATER', 'collar_sweater'), ('GRAPHIC_SHIRT', 'graphic_shirt'), ('HOODIE', 'hoodie'), ('OVERALL', 'overall'), ('SHIRT_CREW_NECK', 'shirt_crew_neck'), ('SHIRT_SCOOP_NECK', 'shirt_scoop_neck'), ('SHIRT_V_NECK', 'shirt_v_neck'), ('ASTRONAUT_SUIT', 'astronaut_suit'), ('BOND_SUIT', 'bond_suit'), ('CHEF', 'chef'), ('GLADIATOR', 'gladiator'), ('JEDI_ROBE', 'jedi_robe'), ('SHIRT_WICK', 'shirt_wick')], default='HOODIE', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hair_type',
            field=models.CharField(choices=[('NONE', 'no_hair'), ('BIG_HAIR', 'big_hair'), ('BOB', 'bob'), ('BUN', 'bun'), ('CAESAR_SIDE_PART', 'caesar_side_part'), ('CAESAR', 'caesar'), ('CURLY', 'curly'), ('CURVY', 'curvy'), ('DREADS', 'dreads'), ('FRIDA', 'frida'), ('FRIZZLE', 'frizzle'), ('FRO_BAND', 'fro_band'), ('FRO', 'fro'), ('LONG_NOT_TOO_LONG', 'long_not_too_long'), ('MIA_WALLACE', 'mia_wallace'), ('SHAGGY_MULLET', 'shaggy_mullet'), ('SHAGGY', 'shaggy'), ('SHAVED_SIDES', 'shaved_sides'), ('SHORT_CURLY', 'short_curly'), ('SHORT_DREADS_1', 'short_dreads_1'), ('SHORT_DREADS_2', 'short_dreads_2'), ('SHORT_FLAT', 'short_flat'), ('SHORT_ROUND', 'short_round'), ('SHORT_WAVED', 'short_waved'), ('SIDES', 'sides'), ('STRAIGHT_1', 'straight_1'), ('STRAIGHT_2', 'straight_2'), ('STRAIGHT_STRAND', 'straight_strand'), ('ASTRONAUT', 'astronout'), ('BRAIDS', 'braids'), ('BRIDE', 'bride'), ('BUZZCUT', 'buzzcut'), ('CORNROWS', 'cornrows'), ('CURLY_2', 'curly_2'), ('DREADLOCKS', 'dreadlocks'), ('EINSTEIN_HAIR', 'einstein_hair'), ('ELVIS', 'elvis'), ('EVIL_SPIKE', 'evil_spike'), ('HALF_SHAVED', 'half_shaved'), ('HAT', 'hat'), ('LONG_HAIR_CURLY', 'long_hair_curly'), ('LOOSE_HAIR', 'loose_hair'), ('MOHAWK', 'mohawk'), ('MOWGLI', 'mowgli'), ('PIXIE', 'pixie'), ('POMPADOUR', 'pompadour'), ('QUIFF', 'quiff'), ('TWIST_LONG_HAIR', 'twist_long_hair'), ('TWIST_LONG_HAIR_2', 'twist_long_hair_2'), ('WICK', 'wick'), ('WILD', 'wild')], default='BOB', max_length=30),
        ),
    ]
