# Generated by Django 5.1.4 on 2025-02-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_clothing_alter_profile_hair_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
