# Generated by Django 5.1.4 on 2025-02-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pip_quote',
            field=models.CharField(blank=True, help_text='A pip for your profile!', max_length=150, null=True),
        ),
    ]
