# Generated by Django 5.1.4 on 2025-02-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_pip_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='teaching_place',
        ),
    ]
