# Generated by Django 5.1.4 on 2025-03-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_profile_teaching_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team_joined',
            field=models.BooleanField(default=False),
        ),
    ]
