# Generated by Django 5.1.4 on 2025-03-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_team_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='join_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
