# Generated by Django 5.1.4 on 2025-03-17 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_remove_team_avatar_team_logo'),
        ('users', '0013_profile_join_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_profile', to='teams.team'),
        ),
    ]
