# Generated by Django 5.1.4 on 2025-03-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_customuser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='team_join_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
