# Generated by Django 5.1.4 on 2025-04-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customuser_team_join_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ysa_way_passed',
            field=models.BooleanField(default=False),
        ),
    ]
