# Generated by Django 5.1.4 on 2025-05-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_customuser_ysa_way_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points_transferred',
            field=models.BooleanField(default=False),
        ),
    ]
