# Generated by Django 5.1.4 on 2025-05-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_profile_points_transferred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='points_transferred',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
