# Generated by Django 5.1.4 on 2025-01-14 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='points',
            name='points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='points',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
