# Generated by Django 5.1.4 on 2025-01-24 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_profile_completed_profile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL),
        ),
    ]
