# Generated by Django 5.1.4 on 2025-01-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='end_time',
            field=models.TimeField(default='01:00:00'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='start_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
