# Generated by Django 5.1.4 on 2025-01-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='generated_avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
