# Generated by Django 5.1.4 on 2026-04-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(choices=[('NGSS', 'NGSS'), ('NC', 'North Carolina'), ('MD', 'Moldova'), ('OTHER', 'Other')], default='NGSS', max_length=20)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('grade_band', models.CharField(blank=True, help_text='e.g. 6–8, 9–12', max_length=50)),
                ('subject', models.CharField(blank=True, help_text='e.g. Earth Science, Physical Science', max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['framework', 'code'],
                'unique_together': {('framework', 'code')},
            },
        ),
    ]
