# Generated by Django 5.1.4 on 2025-06-14 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualpoints',
            name='team',
        ),
        migrations.RemoveField(
            model_name='individualpoints',
            name='user',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='IndividualPoints',
        ),
    ]
