# Generated by Django 5.1.4 on 2025-04-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_program_activity_programregistration_teachingrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programregistration',
            name='difficulty_level',
            field=models.CharField(default='Explorer', max_length=100),
        ),
        migrations.AddField(
            model_name='programregistration',
            name='estimated_time',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programregistration',
            name='external_links',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programregistration',
            name='investigation_procedure',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programregistration',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programregistration',
            name='materials',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programregistration',
            name='moldovan_standards',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programregistration',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programregistration',
            name='us_standards',
            field=models.TextField(blank=True),
        ),
    ]
