# Generated by Django 5.1.4 on 2025-04-28 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_programregistration_difficulty_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='programregistration',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='programregistration',
            name='estimated_time',
        ),
        migrations.RemoveField(
            model_name='programregistration',
            name='external_links',
        ),
        migrations.RemoveField(
            model_name='programregistration',
            name='investigation_procedure',
        ),
        migrations.RemoveField(
            model_name='programregistration',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='programregistration',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='programregistration',
            name='moldovan_standards',
        ),
        migrations.RemoveField(
            model_name='programregistration',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='programregistration',
            name='us_standards',
        ),
        migrations.AddField(
            model_name='program',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='programs.theme'),
        ),
    ]
