# Generated by Django 5.1.4 on 2025-04-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_theme_remove_programregistration_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='is_ysa_way_theme',
            field=models.BooleanField(default=False),
        ),
    ]
