# Generated by Django 5.1.4 on 2025-04-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_theme_is_ysa_way_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='is_ysa_way_theme',
        ),
        migrations.AddField(
            model_name='theme',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme_backgrounds/'),
        ),
    ]
