# Generated by Django 5.1.4 on 2025-05-06 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_alter_program_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='classrooms',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='program',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='description',
        ),
        migrations.AddField(
            model_name='activity',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='resource_file',
            field=models.FileField(blank=True, null=True, upload_to='activity_files/'),
        ),
        migrations.AddField(
            model_name='program',
            name='difficulty_level',
            field=models.CharField(choices=[('Explorer', 'Explorer'), ('Ambassador', 'Ambassador')], default='Explorer', max_length=50),
        ),
        migrations.AddField(
            model_name='program',
            name='estimated_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='materials',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='moldovan_standards',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='us_standards',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='is_locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='programs.theme'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theme',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='themes/backgrounds/'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
