# Generated by Django 5.1.4 on 2025-05-07 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_editrequest_delete_editprogramrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guided_activities', to='programs.program')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_key', models.CharField(choices=[('pre_lab', 'Pre-Lab Activity'), ('observation', 'Observation'), ('idea', 'Idea'), ('hypothesis', 'Hypothesis'), ('experiment', 'Experiment'), ('results_analysis', 'Results and Analysis'), ('communication', 'Communication')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('external_link', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='programs.guidedactivity')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('activity', 'step_key')},
            },
        ),
        migrations.CreateModel(
            name='StepResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='programs.activitystep')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('step', 'student')},
            },
        ),
    ]
