# Generated by Django 5.1.4 on 2025-05-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0012_guidedactivity_activitystep_stepresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystep',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='activity_files/'),
        ),
        migrations.AddField(
            model_name='stepresponse',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='step_videos/'),
        ),
        migrations.AlterField(
            model_name='stepresponse',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
