# Generated by Django 5.1.4 on 2025-05-08 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_activitystep_attached_file_stepresponse_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_lab', models.TextField(blank=True)),
                ('observation', models.TextField(blank=True)),
                ('idea', models.TextField(blank=True)),
                ('hypothesis', models.TextField(blank=True)),
                ('experiment', models.TextField(blank=True)),
                ('analysis', models.TextField(blank=True)),
                ('communication', models.TextField(blank=True)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigation', to='programs.program')),
            ],
        ),
    ]
