# Generated by Django 5.1.4 on 2025-05-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0014_investigationprocedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationprocedure',
            name='analysis_file',
            field=models.FileField(blank=True, null=True, upload_to='investigation_files/'),
        ),
        migrations.AddField(
            model_name='investigationprocedure',
            name='analysis_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationprocedure',
            name='communication_file',
            field=models.FileField(blank=True, null=True, upload_to='investigation_files/'),
        ),
        migrations.AddField(
            model_name='investigationprocedure',
            name='communication_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationprocedure',
            name='experiment_file',
            field=models.FileField(blank=True, null=True, upload_to='investigation_files/'),
        ),
        migrations.AddField(
            model_name='investigationprocedure',
            name='experiment_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationprocedure',
            name='hypothesis_file',
            field=models.FileField(blank=True, null=True, upload_to='investigation_files/'),
        ),
        migrations.AddField(
            model_name='investigationprocedure',
            name='hypothesis_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationprocedure',
            name='idea_file',
            field=models.FileField(blank=True, null=True, upload_to='investigation_files/'),
        ),
        migrations.AddField(
            model_name='investigationprocedure',
            name='idea_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationprocedure',
            name='observation_file',
            field=models.FileField(blank=True, null=True, upload_to='investigation_files/'),
        ),
        migrations.AddField(
            model_name='investigationprocedure',
            name='observation_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationprocedure',
            name='pre_lab_file',
            field=models.FileField(blank=True, null=True, upload_to='investigation_files/'),
        ),
        migrations.AddField(
            model_name='investigationprocedure',
            name='pre_lab_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
