# Generated by Django 5.1.4 on 2025-05-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0015_investigationprocedure_analysis_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystep',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activitystep',
            name='step_type',
            field=models.CharField(choices=[('short_answer', 'Short Answer'), ('long_answer', 'Long Answer'), ('fill_blank', 'Fill in the Blank'), ('multiple_choice', 'Multiple Choice'), ('video', 'Video Response')], default='short_answer', max_length=30),
        ),
    ]
