# Generated by Django 5.1.4 on 2025-05-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0017_activitystep_choices_activitystep_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitystep',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='activitystep',
            name='title',
        ),
    ]
