# Generated by Django 5.1.4 on 2025-05-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0018_remove_activitystep_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidedactivity',
            name='overview',
            field=models.TextField(),
        ),
    ]
