# Generated by Django 5.1.4 on 2025-05-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0019_alter_guidedactivity_overview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activitystep',
            unique_together=set(),
        ),
    ]
