# Generated by Django 5.1.4 on 2025-05-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0020_alter_activitystep_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidedactivity',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
