# Generated by Django 5.1.4 on 2025-05-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0021_alter_guidedactivity_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingrequest',
            name='has_completed',
            field=models.BooleanField(default=False),
        ),
    ]
