# Generated by Django 5.1.4 on 2025-05-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0023_programcreationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='programcreationrequest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programcreationrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programcreationrequest',
            name='title',
            field=models.CharField(default='Untitled Program', max_length=255),
            preserve_default=False,
        ),
    ]
