# Generated by Django 5.1.4 on 2025-06-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0024_programcreationrequest_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programregistration',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programregistration',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachingrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachingrequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
