# Generated by Django 5.1.4 on 2025-07-18 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0027_goal_guidedactivity_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidedactivity',
            name='goal',
        ),
        migrations.AddField(
            model_name='program',
            name='goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='programs.goal'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='programs.program'),
        ),
    ]
