# Generated by Django 5.1.4 on 2025-07-29 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DishReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_waste', models.FloatField(default=0.0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodwaste.dish')),
            ],
        ),
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_reason', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('dishes', models.ManyToManyField(to='foodwaste.dish')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DishWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_percentage', models.PositiveSmallIntegerField(choices=[(0, '0%'), (25, '25%'), (50, '50%'), (75, '75%'), (100, '100%')])),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐')], default=0)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodwaste.dish')),
                ('food_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_wastes', to='foodwaste.foodentry')),
            ],
            options={
                'unique_together': {('food_entry', 'dish')},
            },
        ),
    ]
