# Generated by Django 5.1.4 on 2025-11-18 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundResearchLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_links', to='curriculum.theme')),
            ],
        ),
        migrations.CreateModel(
            name='GuidedResearchActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guided_activities', to='curriculum.theme')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField(blank=True)),
                ('document_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('theme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_guide', to='curriculum.theme')),
            ],
        ),
    ]
