# Generated by Django 5.1.4 on 2025-11-18 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_backgroundresearchlink_guidedresearchactivity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guidedresearchactivity',
            old_name='instructions',
            new_name='analysis',
        ),
        migrations.RenameField(
            model_name='guidedresearchactivity',
            old_name='summary',
            new_name='communication',
        ),
        migrations.AddField(
            model_name='guidedresearchactivity',
            name='hypothesis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guidedresearchactivity',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guidedresearchactivity',
            name='objectives',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guidedresearchactivity',
            name='observation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guidedresearchactivity',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guidedresearchactivity',
            name='question',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guidedresearchactivity',
            name='test',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ResearchMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_list', to='curriculum.guidedresearchactivity')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards_list', to='curriculum.guidedresearchactivity')),
            ],
        ),
    ]
