# Generated by Django 5.1.4 on 2025-11-18 18:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_rename_instructions_guidedresearchactivity_analysis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guidedresearchactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guidedresearchactivity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guided_activities_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guidedresearchactivity',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guidedresearchactivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
