# Generated by Django 5.1.4 on 2025-11-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_guidedresearchactivity_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchmaterial',
            name='text',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='researchstandard',
            name='text',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
