name: Notify Slack on Push or Pull Request

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
    - name: Send notification to Slack
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        if [[ $GITHUB_EVENT_NAME == "push" ]]; then
          MESSAGE="A new push was made by $GITHUB_ACTOR to the branch $GITHUB_REF."
        elif [[ $GITHUB_EVENT_NAME == "pull_request" ]]; then
          MESSAGE="A pull request titled '$PR_TITLE' was $PR_ACTION by $GITHUB_ACTOR."
        fi

        curl -X POST -H 'Content-type: application/json' \
        --data "{\"text\": \"$MESSAGE\"}" \
        $SLACK_WEBHOOK_URL
